coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 100%

ignore:
  - "crates/sentinel-derive/"
  - "tests/"
  - "crates/sentinel-driver/src/connection/"
  - "crates/sentinel-driver/src/tls/"
  - "crates/sentinel-driver/src/lib.rs"
  - "crates/sentinel-driver/src/cancel.rs"
  - "crates/sentinel-driver/src/copy/mod.rs"
  - "crates/sentinel-driver/src/notify/mod.rs"
  - "crates/sentinel-driver/src/pool/mod.rs"
  - "crates/sentinel-driver/src/pipeline/mod.rs"
  - "crates/sentinel-driver/src/stream.rs"
